#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap
cd asyncdb
psql -d postgres -f setup.sql
alembic upgrade head