"""Added oauth2 tables

Revision ID: 1bb8d490a8b5
Revises: 
Create Date: 2024-01-17 23:45:52.898067

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1bb8d490a8b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sqlmodel.GUID(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_blocked', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('username', sqlmodel.AutoString(), nullable=False),
                    sa.Column('password', sqlmodel.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('authorization_codes',
                    sa.Column('id', sqlmodel.GUID(), nullable=False),
                    sa.Column('code', sqlmodel.AutoString(), nullable=False),
                    sa.Column('client_id', sqlmodel.AutoString(), nullable=False),
                    sa.Column('redirect_uri', sqlmodel.AutoString(), nullable=False),
                    sa.Column('response_type', sqlmodel.AutoString(), nullable=False),
                    sa.Column('scope', sqlmodel.AutoString(), nullable=False),
                    sa.Column('auth_time', sa.Integer(), nullable=False),
                    sa.Column('expires_in', sa.Integer(), nullable=False),
                    sa.Column('code_challenge', sqlmodel.AutoString(), nullable=True),
                    sa.Column('code_challenge_method', sqlmodel.AutoString(), nullable=True),
                    sa.Column('nonce', sqlmodel.AutoString(), nullable=True),
                    sa.Column('user_id', sqlmodel.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_authorization_codes_id'), 'authorization_codes', ['id'], unique=True)
    op.create_table('clients',
                    sa.Column('id', sqlmodel.GUID(), nullable=False),
                    sa.Column('client_id', sqlmodel.AutoString(), nullable=False),
                    sa.Column('client_secret', sqlmodel.AutoString(), nullable=False),
                    sa.Column('grant_types', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('response_types', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('redirect_uris', sa.ARRAY(sa.String()), nullable=True),
                    sa.Column('scope', sqlmodel.AutoString(), nullable=False),
                    sa.Column('user_id', sqlmodel.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=True)
    op.create_table('tokens',
                    sa.Column('id', sqlmodel.GUID(), nullable=False),
                    sa.Column('access_token', sqlmodel.AutoString(), nullable=False),
                    sa.Column('refresh_token', sqlmodel.AutoString(), nullable=False),
                    sa.Column('scope', sqlmodel.AutoString(), nullable=False),
                    sa.Column('issued_at', sa.Integer(), nullable=False),
                    sa.Column('expires_in', sa.Integer(), nullable=False),
                    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=False),
                    sa.Column('client_id', sqlmodel.AutoString(), nullable=False),
                    sa.Column('token_type', sqlmodel.AutoString(), nullable=False),
                    sa.Column('revoked', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sqlmodel.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_authorization_codes_id'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
